# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_auto_20160412_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='priceOutIVA',
            new_name='priceWithoutIVA',
        ),
    ]
